# Generated by Django 4.1.5 on 2023-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=30)),
                ('confirma_senha', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
